### ISSUE TITLE
EUR/BTC liquidity bootstrap week

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#12] opened 2017-12-06 20:51 UTC
## Learning Goal/Objective
If we provide enough liquidity for the EUR/BTC order book, we bootstrap the market for organic growth.

## Hypothesis
If the experiment is successful, we predict to the total volume to grow by x (everyone placed its own bet) percent.

## Experiment Design
Every participant on the experiment tries to keep two offers (1 buy, 1 sell with low distance from market price) open all the time to provide liquidity.

## Resource Estimation and Probability
Low personal effort and High probability that it will succeed.

## Results
We have the final numbers for last weeks growth experiment! Comparing trading volume of the last 7 days (7th-13th of Dec) compared to the 7 days (30th Nov - 6th of Dec) before we see following growth:

Market|Growth in Volume|Growth in BTC|Growth in # of Trades
-------|------------------|--------------|----------------------
EUR_BTC|+64%| +22%|+48%
USD_BTC|+54%|+4.1%|
BTC_XMR|+279%|+173%|
All Markets|+143%|+73%|

<img width="672" alt="EUR Trade Volume" src="https://user-images.githubusercontent.com/170962/33978250-1eb1d276-e09f-11e7-9de0-237fdec93fa2.png">

_EUR trade volume 22th Nov - 13th Dec '17 from [Reporting Spreadsheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit#gid=279463428?usp=sharing)_

## Learnings
> _-What did we learn by running this experiment?_

## Action Items
> _- Another experiment for this goal?_
> _- How do we progress from here on?_

**Comment by ripcurlx** [comment] 2017-12-07 11:34
Current Weekly Growth Bets

User|BTC Volume Growth|EUR Volume Growth
----|---------------------|-------------------
ripcurlx|+30%|+50%
mkarrer|+42%|+66%
meapistol|+/-0%|+10%

**Comment by csacher** [comment] 2017-12-07 11:39
BTC Growth: 49%
EUR Growth: 75%

**Comment by mrosseel** [comment] 2017-12-07 11:43
BTC: 10%
EUR: 20%
TRADES: 30%

**Comment by cbeams** [comment] 2017-12-07 13:09
BTC volume growth: +25%
EUR volume growth: +50%
# of (BTC/EUR) trades growth: +50%

P.S.: @ripcurlx, please @mention users wherever possible, e.g. in the User column in the table above, as it ensures folks get notified, reduces chances of typos, etc, thanks.

**Comment by ripcurlx** [comment] 2017-12-12 09:33
Please add your learnings as a comment to this experiment issue. I’ll consolidate them before our next growth meeting tomorrow.

**Comment by ripcurlx** [comment] 2017-12-12 09:34
Learnings:
- it's difficult to get an overlook on how much you've gained/lost with all the trades
- there is no easy way to find out the trading fee paid after a trade is completed or in progress
- the mining fee is the bigger part/influencer of the trading costs
- selling offers with a high distance (2.5%) is faster than having the same spread on buy offers (varies a lot depending on market situation)
- offers with =< 1% distance are picked up quickly (minutes to hours)
- delayed blockchain confirmations slows down the trading process a lot and gets people scared if they loose their funds
- to keep two open offers available all the time requires lots of BTC because of the slow settlement speed of SEPA payments

**Comment by mrosseel** [comment] 2017-12-12 09:42
My learning: tx fees and to a lesser extent Bisq fees put non-intuitive constraints to the offer value+distance combo. We should put this into a spreadsheet and play with it so we can give recommendations to localbitcoin traders/adjust fee structures/...

**Comment by flix1** [comment] 2017-12-12 10:43
Market making milestones:

*Phase 1:* Minimal order book (1 offer on each side, spread < 10%, total offered > 0.1 BTC)
*Phase 2:* Retail order book (10 offers on each side, spread < 3%, total offered > 5 BTC)
*Phase 3:* Trading order book (20 offers on each side, spread < 1%, total offered > 10 BTC) 
*Phase 4:* Wholesale order book (50 offers per side, spread < 0.5%, total offered > 50 BTC)
*Phase 5:*  Institutional order book (100 offers per side, spread < 0.25%, total offered > 100 BTC)

I believe that even reaching and staying at Phase 3 would make Bisq a huge sucess... but each jump requires organic growth, plus a push...

**Comment by flix1** [comment] 2017-12-12 10:44
EUR/BTC is at Phase 2. I believe if we manage to keep it there for a few weeks and at the same time push to attract localbitcoin traders we can get it to level 3 in January.

Then we need to focus on USD/BTC. I know it's difficult... but breaking the USD market is a key challenge.

**Comment by flix1** [comment] 2017-12-12 11:02
Learnings:
-Bitcoin network congestion kills usability of Bisq
-Low spread (<1%), small quantity (0.01) offers are taken very quickly.
-Even when price volatility is high and confirmation was delayed, promises were fulfilled.
-Nobody is using SEPA Instant Payments yet.

**Comment by flix1** [comment] 2017-12-12 11:06
One of my trades remained unconfirmed for over 6 days:
06ad9f232a1f955a03c129417a458459fed03a74a04e492a9f16fae9ad6d1135

On the other hand I did another on Monday, after mempool had cleared, and completed everything within 24 hours. SEPA can be fast!

**Comment by ManfredKarrer** [comment] 2017-12-13 18:47
@flix1 We adjusted the fee estimations. So your first trade was probably with the old fee estimations where we have been a bit too low with recent congestion.

**Comment by ManfredKarrer** [comment] 2017-12-13 19:10
Learnings:
- We need to adjust faster to fee situation. We increased fees now a lot to get fast confirmations but that drives up total trade fee. So we need to go back asap. Fee estimation services are still very bad and most time they suggest way too high fees. We will try to make some automated adjustments (e.g. if mempool gets filled we increase). Finding an experienced Bitcoin dev in that area would be good.
- I provided XMR only as I was traveling an had no access to my EUR bank. Most offers were taken quickly and I also took a few. 
- When we get more users, arbitration will become a bottleneck as well as general costumer care and support (Forum). There are some technical issues with timeouts I am investigating atm. Infrastructure of seednodes, price relay nodes and BTC nodes is not stable enough atm and need to be improved. We cannot grow faster as our technical capacities allow. Atm there are too few devs who can fix bugs or find out the reason for the issues which happened in the last 1-2 weeks. We need to scale on the dev front before we can scale on the user base. Dispute cases caused due technical issues (or too low fees) need to be solved otherwise we get stuck there. Dispute cases due usability issues should also be addressed. Many things are still not well enough explained/clear to users.
- If I lose too much time on bugfixing/improvements work on the DAO will get further delayed and attracting more devs is harder as if we would have the DAO already completed (another chicken/egg problem).
- Not directly a result of that experiment but a part of some of the problems (bugs): Decentralizing operations (seeds, price nodes, btc nodes) is harder as expected. Getting to the required quality of service has high priority as well a monitoring it. E.g. the timeout problems might be related to instable overloaded btc nodes (still investigating). So those issues cause serious problems for users (lost trade fee) -> more support work -> lose users if we cannot handle it well.

**Comment by ManfredKarrer** [comment] 2017-12-13 19:13
Btw. Altcoin trade can be quite fast. Just did 3 and got all completed in < 5 min.

**Comment by cbeams** [comment] 2017-12-13 19:14
My Learnings: 

 - My four offers to sell 0.5–0.25 BTC @ 1% distance from market price were taken within roughly 24 hours
 - They took ages to settle (actually the last two just settled today) because of the fee / congestion issue and slow tx confirmation times that resulted.
 - I placed no further trades throughout the week than those initial four, so I essentially dropped out / didn't participate to plan

I believe it was altogether an unfortunate week to attempt such an experiment. The massive price action caused a natural influx of volume, making it hard to distinguish our actions from everyone else's, and then slow conf times threw a wrench in everything.

**Comment by ripcurlx** [comment] 2017-12-14 07:00
And the winner of our experiment estimation bet is @cbeams with a total difference of 17% to the final numbers!

2nd place (ex aequo): @ManfredKarrer & @ripcurlx (22% distance)

_Number # Trades Growth side bet_:
Winner is @ManfredKarrer with 8% distance!

**Comment by cbeams** [comment] 2017-12-18 11:03
Closing as complete. Thanks all who participated.

**Closed by cbeams** 2017-12-18 11:03 UTC
Labels: experiment

**Comment by flix1** [comment] 2018-04-23 08:41
5 months after this, on April 23rd, we have 50+ offers in the EUR/BTC order book.  

![image](https://user-images.githubusercontent.com/4233784/39115677-b7f97cf0-46e2-11e8-9336-b68c1de60de6.png)

This market is the first to achieve **Liquidity Level 3**.
![image](https://user-images.githubusercontent.com/4233784/39115712-d6d7c9ba-46e2-11e8-99ee-d626e7b26534.png)

**Comment by flix1** [comment] 2018-04-23 08:43
We should be able to speed things up now that we know how it's done. A reasonable target should be to push the next market (USD) to **liquidity level 3** in 3 months.
